version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - api-db:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  api-db:
